services:
  db:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../configs/.env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
